theme: jekyll-theme-cayman
title: A Noob's Journey into Gamedev
description: A chronological record of one person's attempts to learn Unity
# Apply this change to _config.yml file
kramdown:
  # parse markdown inside block-level HTML tag
  parse_block_html: true

sass:
    style: :compressed

baseurl: /30days-unity2d